# credit:
# https://github.com/sindresorhus/execa/blob/main/.github/workflows/main.yml
name: Tests
on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - lts/*
          - latest
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install deps (windows only)
        if: matrix.os == 'windows-latest'
        run: |
          choco install pdftk-java --params "'/AddToUserPath:yes /AddToSystemPath:yes'"
          choco install mupdf

      - name: install deps (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install pdftk-java
          sudo apt install mupdf-tools

      - name: install deps (macos only)
        if: matrix.os == 'macos-latest'
        run: |
          brew install pdftk-java
          brew install mupdf

      - run: pnpm install

      - name: test
        shell: bash
        run: |
          export PATH="/c/tools/pdftk-java:$PATH"
          pnpm test-mocha
          pnpm lint || pnpm fmt

      - name: Pack cli
        run: pnpm pack

      - name: Install cli
        shell: bash
        run: npm i -g ./bader-nasser-pdftools-*.tgz

      - name: Use cli
        shell: bash
        run: |
          export PATH="/c/tools/pdftk-java:$PATH"
          pdf-tools -h
          pdf-tools p -h
          pdf-tools p test/docs/data.json
          pdftools m test/pdfs/input-*.pdf -o output.pdf -c
          pdftools m2 test/pdfs/input-*.pdf -o output2.pdf -c
          pdftools m2 test/pdfs/input-*.pdf test/pdfs/input-2.pdf 2 -o output3.pdf -cl
